application-description: Rezztoran
application-version: 1.0


server:
  error:
    whitelabel:
      enabled: false
  port: 8082
spring:
  config:
    activate:
      on-profile: local_env
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/rezztoran?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      schedule-group-id: group
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumers:
      default-group-id: group
      scheduler-group-id: scheduler
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      book-created: book-created
      password-reset: password-reset



jwt-variables:
  EXPIRES_ACCESS_TOKEN_MINUTE: 200000
  ISSUER: rezztoran
  KEY: rezztoran
logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        web: DEBUG
mail:
  address: MAIL
  password: PASSWORD
springdoc:
  swagger-ui:
    path: /swagger-ui.html