application-description: Rezztoran
application-version: 1.0

server:
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:h2:mem:database
  h2:
    console:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    
jwt-variables:
  EXPIRES_ACCESS_TOKEN_MINUTE: 200000
  ISSUER: rezztoran
  KEY: rezztoran
logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        web: DEBUG
mail:
  address: MAIL
  password: PASSWORD
